### ISSUE TITLE
Windows 8.1 Universal Application

### ISSUE THREAD

**Issue by RTPeat** [aritchie/acrmvvmcross#20]
I'm trying to use the UserDialogs plugin on a Windows 8.1 Universal Application with both Windows 8.1 and Windows Phone 8.1 projects. Whilst the Nuget packages install, when I try and initialise the plugin I get the following exception thrown:

could not load plugin assembly for type Acr.MvvmCross.Plugins.UserDialogs.PluginLoader

**Comment by SirDev** [comment]
@aritchie I've got this same issue with a simple Win 8.1 Silverlight application (which is not universal). I got the same error message as @RTPeat describes. It should work on a regular WP-app shouldn't it ? the Nuget package installs without any hickups.

**Comment by aritchie** [comment]
4.0 only just added a very early beta for UAP and WPA81, not silverlight.  It is likely that only the PCL support is installing.

**Comment by SirDev** [comment]
I see. I merely thought that since you said "I support winphone, but not windows" that you ment "I support WP Silverlight 7/8/8.1". It looks like it should be working, should it?

![image](https://cloud.githubusercontent.com/assets/2150482/9313443/575581be-4523-11e5-968a-f94e569d292b.png)

**Comment by aritchie** [comment]
3.x does support windows phone

**Comment by SirDev** [comment]
Ah right! Thank you, and thanks for the great work here!

**Comment by sergiohj** [comment]
Hello, I have the same issue in a WP81 Silverlight. How can I go back to the 3.X version to fix this issue?

**Comment by aritchie** [comment]
@sergiohj Use nuget and set the version to 3.4.2

**Comment by sergiohj** [comment]
Hi, I'm using the next command Install-Package Acr.MvvmCross.Plugins.UserDialogs -Version 3.4.2 but I get the next error:

Unable to find version '3.4.2' of package 'Acr.MvvmCross.Plugins.UserDialogs'.

**Comment by Cheesebaron** [comment]
NuGet had problems with their CDN yesterday, it should be fixed.

**Comment by aritchie** [comment]
Just the wrong version.  You want 3.1.0.  As it is, I'm going to put out a gimped WP8 release.  @sergiohj if you ever need to know what versions are available, just go to https://www.nuget.org/packages/Acr.MvvmCross.Plugins.UserDialogs/ or any other nuget package for that matter.

**Comment by aritchie** [comment]
@SirDev @sergiohj  please try the package today.  I have restored wp8 SL support.  The package does not support win8, only wp8.  UWP will be supported in the near future.
