### ISSUE TITLE
[Settings Plugin - Android] System.ArgumentException: kls must not be IntPtr.Zero

### ISSUE THREAD

**Issue by StevenHanquez** [aritchie/acrmvvmcross#24]
Hi,

Every time I call Get, Set or Resync method, an exception is thrown:
"System.ArgumentException: 'kls' must not be IntPtr.Zero. Parameter name: kls"

![issue_settings_plugin](https://cloud.githubusercontent.com/assets/5033972/5313952/1d0cc964-7c6e-11e4-844a-b1df3762ffeb.png)

**Comment by aritchie** [comment]
I've looked at this further and the only thing I can think of is that you are storing something too big to store in the settings value.  Anyone with a repro sample yet?

**Comment by aritchie** [comment]
I have never received anything for this, nor have I ever had this issue.  I've seen jobject exceptions as well usually relating to memory leaks of some sort.

**Comment by Cheesebaron** [comment]
This issue is fixed in my Settings plugin. It has something to do with keeping a reference to `SharedPreferences`. Instead dispose of it immediately and you should be golden.

**Comment by aritchie** [comment]
Ahhh most excellent.  Thanks @Cheesebaron 
I still have never seen the error and I use this library in literally every mobile I have worked on.

**Comment by Cheesebaron** [comment]
@munkii had a sample here: https://github.com/munkii/SettingsWithAzureRepro The trigger was adding some Azure library and instantiate it. Then it threw the errors, however internally, they didn't bubble up. The effect was that the settings value never was retrieved. Changing it to disposing after using `SharedPreferences` it fixed the problem. So if someone still experiences this, you could try doing so as well.

**Comment by aritchie** [comment]
FYI - This issue was fixed over in Acr.DeviceInfo (https://github.com/aritchie/deviceinfo) and is available on nuget
