### ISSUE TITLE
Loading IProgressDialog orientation on iOS 

### ISSUE THREAD

**Issue by absolutx13** [aritchie/acrmvvmcross#26]
Seems like when calling IUserDialogService.Loading() on iOS under all orientations but one, the text shows up sideways or upside down. This was reproduced on iOS 8 on an iPad Air.

**Comment by aritchie** [comment]
Check and make sure you are using the latest BTProgressHUD.  It may not be included at the moment.  The latest version is 1.15

**Comment by absolutx13** [comment]
Seems to be fine after updating the BTProgressHUD to 1.15. Thanks
