### ISSUE TITLE
GetTopViewController return wrong ViewController when you have a modal + navigation controller

### ISSUE THREAD

**Issue by RTodorov** [aritchie/acrmvvmcross#28]
Hi,

I'm having the infamous "Attempt to present UIAlertController on UINavigationController whose view is not in the window hierarchy!" error on the following scenario:

UITabBarController + UINavigationController (A)
    |-> (modal) UINavigationController (B) --> (UserDialogs.Alert() call here)

I found out that, on iOS 8, GetTopViewController() is returning the UINavigationController under the modal view (A) instead of (B). on iOS 7, it returns null!

Any clues?

**Comment by aritchie** [comment]
Move to Acr.UserDialogs

**Comment by RTodorov** [comment]
Thanks a lot @aritchie !
