### ISSUE TITLE
UserDialogService Login issue

### ISSUE THREAD

**Issue by rcbeyra** [aritchie/acrmvvmcross#30]
On the result action (OnResult) from the Login user dialog, the bool property OK is always TRUE. it doesn't matter if you have clicked OK, or CANCEL, this is critical because is doing the login even if the user wants to cancel.

**Comment by aritchie** [comment]
Switch to acr.userdialogs (https://github.com/aritchie/userdialogs).  The fix was made here a few weeks ago.  This library will basically be wrapping it in the next few weeks.
