### ISSUE TITLE
NetworkPlugin and UserDialogsPlugin missing bootsrapper for iOS

### ISSUE THREAD

**Issue by WarBorg** [aritchie/acrmvvmcross#32]
please be aware that for some reason the nuGet package does not install the bootstrap file for the iOS platform, I only installed these two plugins at the moment but others may have the same problem, thank you

**Comment by PenaPP** [comment]
I have the same problem :(

**Comment by PenaPP** [comment]
I have the same problem, but it also doesn't have bootstrap file and binary (.dll) for WindowsStore project :(

**Comment by aritchie** [comment]
I have never supported windows store.

**Comment by PenaPP** [comment]
Well, then I guess I miss something - there is some implementation here, isn't it?...
https://github.com/aritchie/acrmvvmcross/tree/master/Acr.MvvmCross.Plugins.Network.WindowsStore

**Comment by aritchie** [comment]
I have never finished it and likely never will (at least in this repo)

**Comment by PenaPP** [comment]
And is there a repo with implementation for all platforms (WindowsStore, WindowsPhone, Android, iOS)? I need crossplatform connection type detection.

**Comment by aritchie** [comment]
James Montemagno (https://github.com/jamesmontemagno/Xamarin.Plugins)  has a connectivity package. 

As for the relevant topic here, the issue isn't as straight forward as I thought it would be.

In any case, all of these libraries are being deprecated.  Use the following
- Acr.UserDialogs
- Acr.BarCodes
- Acr.Settings
- Acr.DeviceInfo

**Comment by WarBorg** [comment]
thank you for the notice, does this go for all other plugins as well ?

**Comment by aritchie** [comment]
yes

**Comment by PenaPP** [comment]
Thank you and I'll try the suggested connectivity package ;)

**Comment by WarBorg** [comment]
thank you, but will they work ok with MVVMCross ?

**Comment by PenaPP** [comment]
@WarBorg Let's hope so :)

**Comment by aritchie** [comment]
They are cross platform plugins.  They will work with or without mvvmcross.
