### ISSUE TITLE
BarCode Plugin Generation

### ISSUE THREAD

**Issue by gabrieligbastos** [aritchie/acrmvvmcross#33]
Hi,

Trying to run the sample.Droid. The barcode plugin that generates, it is not working. I'm receiving the "The value is not a valid bitmap" error in Application Output.

Any ideia what should be the problem? The weird thing is that if I copy and paste the code from plugin to the application, and display the bitmap (instead of convert to stream and then convert back in Converter) it works perfect. So, there should be some problem in this conversion that I am not able to get it. I've spent two days already and found no solution for this problem. Any idea?

This error happened in my Genymotion 5.0 emulator and then in my Galaxy S Duos 4.1 also.

Thanks in regards,

**Comment by aritchie** [comment]
Use Acr.BarCodes.  This library is deprecated.  This defect is also addressed in the new library
