### ISSUE TITLE
UserDialogs 2.4.0 does not add iOS Bootstrapper

### ISSUE THREAD

**Issue by geirsagberg** [aritchie/acrmvvmcross#34]
To reproduce:
1. Create an iOS project
2. Add Acr.MvvmCross.Plugins.UserDialogs 2.4.0 via NuGet
3. Note that no Bootstrapper is added to the iOS project.

**Comment by aritchie** [comment]
I'm not sure when/why this happened because I haven't changed anything in a while for this project.  In any case, I'm pushing everyone to Acr.UserDialogs which does not require a bootstrap file

**Comment by geirsagberg** [comment]
With Acr.UserDialogs one needs to manually register IUserDialogs as a service in MvvmCross though (and also call Init)? I really like the easy way of just adding Mvx plugins and start using them. I noticed there is some work done delegating the implementation to Acr.UserDialogs in the bait-switch branch. Will you be moving forward with this?

**Comment by geirsagberg** [comment]
Looking at the code, it seems the problem was fixed in 8edfbff on 2015-02-05, but the current NuGet package is from 2015-01-18. It would be really cool if you could publish the latest version to NuGet :)

**Comment by aritchie** [comment]
Thanks for finding that.  I honestly glazed over it.  In any case, I skipped a fix and just did the move to Acr.UserDialogs.  The package may have some issues, but 3.0.0 is out in the wild now.

**Comment by geirsagberg** [comment]
Awesome, thanks a bunch! This is my favourite MvvmCross plugin, so elegant :)
