### ISSUE TITLE
does not work with new DeviceInfo nuget version

### ISSUE THREAD

**Issue by softlion** [aritchie/acrmvvmcross#36]

**Comment by lbarbier** [comment]
Any update on this?

The latest DeviceInfo does not work on iOS or Android.

I get the following on iOS:
MTOUCH: errorMT2002: Failed to resolve "Acr.DeviceInfo.IDeviceInfo" reference from "Acr.DeviceInfo, Version 1.0.0.0, Culture=neutral, PublicKeyToken=null"

I get the following on Android:
Could not load type "Acr.DeviceInfo.IDeviceInfo" reference from "Acr.DeviceInfo, Version 1.0.0.0, Culture=neutral, PublicKeyToken=null"

I'm using Nuget package version 2.2.0.

**Comment by aritchie** [comment]
@lbarbier Don't ever bother asking for update timelines.  If you can't wait, fix it yourself.  It's open source!

**Comment by aritchie** [comment]
Updated in 2.0.3
