### ISSUE TITLE
IUserDialogService missing in 4.1.0? 

### ISSUE THREAD

**Issue by tehZeno** [aritchie/acrmvvmcross#38]
Hi,

Acr.MvvmCross.Plugins.UserDialogs v4.1.0 (as released on nuget at https://www.nuget.org/packages/Acr.MvvmCross.Plugins.UserDialogs/4.1.0 ).  Does not seem to contain the IUserDialogService anymore. 

I see this interface does exist and is defined public on the latest version here on github. 
It not working on 4.1.0: Is this a mistake on my part, or is there an issue with 4.1.0 ? 

Thanks!

**Comment by tehZeno** [comment]
There is a IUserDialog that seems to have almost the same signature. Perhaps a temporary move in the '4'-series. Or it might have other issues.

**Comment by aritchie** [comment]
The interface was renamed in version 4

**Comment by tehZeno** [comment]
Thanks for the info!

**Comment by Xempai** [comment]
And was renamed to ?? please :)

**Comment by aritchie** [comment]
IUserDialogs

**Comment by Xempai** [comment]
Thanks Arithie, I found out just after posting my question :).
