### ISSUE TITLE
Network plugin android permissions

### ISSUE THREAD

**Issue by tomcurran** [aritchie/acrmvvmcross#42]
The Network plugin asks for internet permission but should it not ask for network state permission instead?
```
// Acr.MvvmCross.Plugins.Network.Droid/Properties/AssemblyInfo.cs

// current permission
[assembly: UsesPermission(Android.Manifest.Permission.Internet)]

// actual permission ?
[assembly: UsesPermission(Android.Manifest.Permission.AccessNetworkState)]
```

**Comment by aritchie** [comment]
It is irrelevant what the library requests.  You still end up having to request it in your main droid app in any case.  

You should switch to the xamarin connectivity plugin at this point.
